Hopson97/open-builder

src/client/gameplay.cpp

`erase()` invalidates the iterator being erased, so that it can no longer be incremented. This results in an error in debug mode, and possibly other behaviours in release mode.

Fixed Gameplay::update()

---

README.md
scripts/install.sh

Title says it all. The installer should offer support for a wide variety of distributions, making the installation of the project very easy.

Add versatile install script for dependencies

---

src/client/world/chunk_mesh_generation.cpp

"vertices" seems to be the correct plural of "vertex"
https://www.wordhippo.com/what-is/the-plural-of/vertex.html

Fixed typo "verticies -> vertices"

---

src/client/world/chunk_mesh_generation.cpp

Guess I didn't find this one last time. Same exact word

Fix (another) typo

---

src/client/gameplay.cpp

I really want to contribute in other ways, I swear! :)

Fix variable name

---

src/client/client.cpp
src/client/client.h
src/client/network/client_commands.cpp
src/common/common/network/net_command.h
src/server/network/server.cpp
src/server/network/server.h

eg remove unneeded functions and such

refactor the server code a bit

---

.gitignore

Created by cscope and vim plugins.

Ignore tags file

---

src/client/client.cpp

Makes view so that players cannot look upside down.
no jitter when looking straight down continously

fluid look direction correction

---

src/server/network/server.cpp
src/server/world/terrain_generation.cpp
src/server/world/terrain_generation.h

Experimental terrain testing

---

scripts/install.sh

Forgot CMake package under Debian for the automatic installation.

---

src/client/network/client_commands.cpp
src/client/world/chunk_mesh_generation.h
src/common/common/world/chunk.cpp
src/common/common/world/chunk.h
src/server/network/server.cpp

Split out chunk compression from chunk class, and removes a few functions

Tiny chunk refactor

---

shaders/selection_fragment.glsl
shaders/selection_vertex.glsl
src/client/client.cpp
src/client/client.h
src/client/gl/primitive.cpp
src/client/gl/primitive.h
src/client/gl/vertex_array.cpp
src/client/gl/vertex_array.h
src/client/gui/gui.h
src/client/maths.cpp
src/client/maths.h

This adds a selection box around the block the player is currently looking at. This can be used as a visual indicator to see which block the player is pointing at.

Selection box where the player is looking

---

src/client/client.cpp
src/client/network/client_commands.cpp
src/client/world/chunk_mesh_generation.cpp
src/client/world/client_voxel.h
src/server/network/server.cpp
src/server/scripting/server_game_data.cpp
src/server/scripting/server_game_data.h

BEFORE
AFTER
Also rename "meshType" to just "type" for voxels, as it more reflects what it is

Prevent water blocks being breakable

---

CMakeLists.txt
src/client/client.cpp
src/common/common/scripting/script_engine.cpp
src/common/common/scripting/script_engine.h
src/server/network/server.cpp
tests/common/scripting/script_engine_test.cpp

Adds some additional functionality to the script engine class that will allow the running of functions created in the Lua code from the C++ code.
Also adds some unit testing for it

Refactor and Extend the ScriptEngine

---

.clang-format
CMakeLists.txt
src/client/client.cpp
src/client/client.h
src/client/gl/vertex_array.cpp
src/client/network/client_commands.cpp
src/common/common/debug.h
src/common/common/network/command_dispatcher.h
src/common/common/network/net_command.h
src/common/common/world/voxel_registry.h
src/server/network/server.cpp
src/server/network/server.h
tests/common/network/command_dispatcher_test.cpp

Adds a class to execute network commands rather than using a huge switch statement.
Not sure if it is worth like merging this into the NetworkHost class and turning that into a class template, but that's prob just taking it a bit too far lol

Network command dispatcher

---

src/client/client.cpp

[Client] Make the water faces render correctly if player is underwater

---

src/client/client.cpp
src/client/client.h
src/client/maths.cpp
src/client/maths.h

This change replaces the current ray-casting algorithm for block selection with a more precise and versatile voxel traversal algorithm.

Fix for ray inaccuracy when selecting / breaking / placing blocks

---

game/world/common_cactus_gen.lua
game/world/common_tree_gen.lua
game/world/desert_biome.lua
game/world/grassland_biome.lua
src/common/common/CMakeLists.txt
src/common/common/util/random_number_generator.cpp
src/common/common/util/random_number_generator.h
src/server/CMakeLists.txt
src/server/lua/lua_api.h
src/server/lua/util_api.cpp
src/server/network/server.cpp
src/server/world/terrain_generation.cpp

Adds RNG exposure from C++ to the Lua, allowing for things like variable height trees and such
See example below, where the left tree is 5 blocks tall, while the other visible trees are 4 blocks tall.
(Lua already has rng, this is more so that I have control over the rng seed from the world gen)

Add random number generator for Lua

---

.gitignore
src/client/CMakeLists.txt
src/client/client.cpp
src/client/client.h
src/client/renderer/chunk_renderer.cpp
src/client/renderer/chunk_renderer.h

Moves the chunk rendering stuff out of the client class, into a separate chunk renderer class
This cleans up the client class by a huge amount.

Chunk renderable class

---

src/client/world/chunk_mesh_generation.cpp

Fixed fluids not rendering top-face under a block #156

---

_config.yml
game/client/main.lua
game/client/menus/error_screen.lua
game/client/menus/main_menu.lua
game/client/menus/pause_menu.lua
game/client/menus/transition_screen.lua
src/client/CMakeLists.txt
src/client/client.cpp
src/client/client.h
src/client/client_engine.cpp
src/client/game.cpp
src/client/game.h
src/client/lua/client_lua_callback.cpp
src/client/lua/client_lua_callback.h
src/client/window.cpp

Aims to remove a bunch of un-needed or unused parts of the code, for the sake of simpler refactoring

Reduce code

---

.github/workflows/ccpp.yml
scripts/install.sh

Update to gcc-8 for <filesystem> and <optional>

---

deps/sol/sol.hpp
docs/building/Building_windows_vs.md

[Doc] Tweaked visual studio doc and disabled C4996 warnings in sol

---

src/client/gl/shader.cpp
src/client/gl/shader.h
src/common/common/util/file_io.cpp
src/common/common/util/file_io.h

Reverts Hopson97/open-builder#188

Revert "[Draft] Make the shader compiler error out more verbosely"

---

src/client/gl/shader.cpp
src/client/gl/shader.h
src/common/common/util/file_io.cpp
src/common/common/util/file_io.h

Also gives the Shader::create a strong exception guarantee

Add verbosity to shader compiler's errors

---

.github/workflows/linux.yml
.github/workflows/macos.yml
README.md
scripts/install.sh

Add macOS and Windows continuous integration via GitHub Actions
